### ISSUE TITLE
error[E0432]: unresolved import vmm_sys_util::sock_ctrl_msg

### ISSUE THREAD

**Issue by yurivict** [firecracker-microvm/micro-http#34]
```
error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/connection.rs:16:19
   |
16 | use vmm_sys_util::sock_ctrl_msg::ScmSocket;
   |                   ^^^^^^^^^^^^^ could not find `sock_ctrl_msg` in `vmm_sys_util`

error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/server.rs:15:19
   |
15 | use vmm_sys_util::sock_ctrl_msg::ScmSocket;
   |                   ^^^^^^^^^^^^^ could not find `sock_ctrl_msg` in `vmm_sys_util`

error[E0432]: unresolved import `vmm_sys_util::epoll`
  --> /usr/ports/emulators/firecracker/work/micro-http-4b18a043e997da5b5f679e3defc279fec908753e/src/server.rs:17:5
   |
17 | use vmm_sys_util::epoll;
   |     ^^^^^^^^^^^^^^^^^^^ no `epoll` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `micro_http` due to 3 previous errors
```

rust-1.66.0

**Comment by roypat** [comment]
Hi yurivict, 

thanks for reporting this! May I ask what platform you are compiling on? The `rust-vmm/vmm_sys_utils` epoll and sock_ctrl_msg apis are behind a `cfg(target_os = "linux")`, so micro_http will only successfully compile on linux at the moment. 

Best, 
Patrick

**Comment by yurivict** [comment]
I compile on FreeBSD 13.1

**Comment by roypat** [comment]
Thanks for letting me know! Sadly, `micro-http` is purpose-built for firecracker's use-case, meaning we only support operating systems/kernels matching firecracker's [kernel support policy](https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md). However, you might be able to get micro-http to compile by patching the upstream rust-vmm/vmm-sys-utils project to use FreeBSD's equivalent of epoll/sendpkt/recvpkt.

Please also note that even if you create a version of micro-http that runs on FreeBSD, you will still not be able to run firecracker, as it is tightly coupled to Linux's KVM. 

I am closing this issue, as this is not a bug with micro-http, but rather a consequence of our support policy, but please do reach out if you have additional questions!
